{% set name = "snk" %}
{% set version = "0.27.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snk-{{ version }}.tar.gz
  sha256: 1f8679bb0746c80ef2d466eaca1bb2dc1f7f3a3b4dee760e318fb4064443c179

build:
  entry_points:
    - snk = snk.main:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - typer <=0.9.0
    - gitpython <=3.1.31
    - pulp <2.8
    - ascii-art <=5.9
    - makefun <=1.15.1
    - snk-cli ==0.3.0

test:
  imports:
    - snk
  commands:
    - pip check
    - snk --help
  requires:
    - pip

about:
  home: https://snk.wytamma.com
  summary: Snakemake workflow management system and CLI generation tool
  dev_url: https://github.com/wytamma/snk
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Wytamma
