{% set name = "snk" %}
{% set version = "0.27.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snk-{{ version }}.tar.gz
  sha256: 0ac6adff478694fc30c6cc4c51a7a094a4c91213c78d8f49e1f730cec2c76a7d

build:
  entry_points:
    - snk = snk.main:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - typer >=0.12.0,<0.13.dev0
    - gitpython >=3.1.0,<3.2.dev0
    - snk-cli >=0.3.1,<0.4.dev0

test:
  imports:
    - snk
  commands:
    - pip check
    - snk --help
  requires:
    - pip

about:
  home: https://snk.wytamma.com
  summary: Snakemake workflow management system and CLI generation tool
  dev_url: https://github.com/wytamma/snk
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Wytamma
