{% set name = "snk-cli" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snk_cli-{{ version }}.tar.gz
  sha256: 8a619839afaed3052c688b7daa54b52550cbd18f431a90100e8f17886b98a3a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - snakemake >=7
    - typer >=0.9,<1.dev0
    - gitpython >=3.1,<4.dev0
    - pulp <2.8
    - ascii-art >=5.9,<6.dev0
    - makefun >=1.15,<2.dev0
    - datrie >=0.8.2

test:
  imports:
    - snk_cli
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/snk-cli/
  summary: Generate dynamic Snakemake CLIs
  dev_url: https://github.com/wytamma/snk-cli
  license: MIT
  license_file: LICENSE.txt

extra:
  channels:
    - conda-forge
    - bioconda
  recipe-maintainers:
    - Wytamma
